# Generated by Django 5.2 on 2025-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unverified_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
