# Generated by Django 5.2 on 2025-08-07 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default=datetime.datetime(2025, 8, 7, 9, 38, 26, 126565, tzinfo=datetime.timezone.utc), editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
