# Generated by Django 5.2 on 2025-08-04 11:08

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_unverified_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.vendor_profile_picture_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orderdeliveryconfirmation',
            old_name='business_name',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='orderdeliveryconfirmation',
            old_name='recievers_name',
            new_name='store_address',
        ),
        migrations.RenameField(
            model_name='orderdeliveryconfirmation',
            old_name='vendor_location',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryconfirmation',
            name='vendor_email',
        ),
        migrations.AddField(
            model_name='orderdeliveryconfirmation',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryconfirmation',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryconfirmation',
            name='store_phone',
            field=models.CharField(default=datetime.datetime(2025, 8, 4, 11, 8, 15, 353902, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('fund', 'Funding'), ('withdraw', 'Withdrawal'), ('investment', 'Investment'), ('roi', 'Return On Investment'), ('system', 'System Notification'), ('admin', 'System Admin Notification')], default='system', max_length=50),
        ),
    ]
