# Generated by Django 5.2 on 2025-08-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('fund', 'Funding'), ('withdraw', 'Withdrawal'), ('investment', 'Investment'), ('roi', 'Return On Investment'), ('system', 'System Notification'), ('admin', 'System Admin Notification'), ('order', 'order delivered')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('partner', 'Partner')], default='', max_length=20),
        ),
    ]
