# Generated by Django 5.2 on 2025-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_orderdeliveryconfirmation_store_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=225),
        ),
    ]
