# Generated by Django 5.2 on 2025-08-08 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default=datetime.datetime(2025, 8, 8, 13, 40, 23, 644930, tzinfo=datetime.timezone.utc), editable=False, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
