# Generated by Django 5.2 on 2025-08-05 14:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=datetime.datetime(2025, 8, 5, 14, 59, 13, 777236, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.vendor'),
            preserve_default=False,
        ),
    ]
