# Generated by Django 5.2 on 2025-08-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
