# Generated by Django 5.2 on 2025-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_roipayout_options_product_kg_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(editable=False, max_length=225, unique=True),
        ),
    ]
