# Generated by Django 5.2 on 2025-08-10 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=datetime.datetime(2025, 8, 10, 22, 52, 15, 523516, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.vendor'),
            preserve_default=False,
        ),
    ]
