# Generated by Django 5.2 on 2025-08-10 23:27

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=shop.models.get_default_vendor_pk, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.vendor'),
        ),
    ]
