# Generated by Django 5.2 on 2025-08-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_company_name'),
        ('wallet', '0002_vendorasbeneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.vendor'),
        ),
    ]
