# Generated by Django 5.2 on 2025-08-25 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_company_name'),
        ('wallet', '0003_transaction_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remittance',
            old_name='confirmed_at',
            new_name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='note',
        ),
        migrations.AddField(
            model_name='remittance',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='remittance_id',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='shop.vendor'),
        ),
    ]
