# Generated by Django 5.2 on 2025-05-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='available_balance_at_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
