# Generated by Django 5.2 on 2025-08-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_company_name'),
        ('wallet', '0004_rename_confirmed_at_remittance_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('fund', 'Fund'), ('withdraw', 'Withdraw'), ('investment', 'Investment'), ('investmentUpdate', 'InvestmentUpdate'), ('roi', 'Return On Investment'), ('remittance', 'Remittance')], max_length=20),
        ),
    ]
