# Generated by Django 5.2 on 2025-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_account_name_transaction_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='sort_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.CharField(max_length=200),
        ),
    ]
