# Generated by Django 5.2 on 2025-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_beneficiary_sort_code_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
