from django.urls import path
from .views import *

urlpatterns = [
    path('signup/partner/', SignupView.as_view(), name='partner-signup'),
    path('signin/partner/', SigninView.as_view(), name="partner-signin"),
    path('verify-otp/partner/', VerifyOTPView.as_view(), name="verifyotp"),
    path('forgot-password/partner/', PasswordResetView.as_view(), name="forgot password"),
    # path('reset-password-otp/partner/', ResetPasswordWithOTPView.as_view(), name="reset password"),
    path('change-password/partner/', ChangePasswordView.as_view(), name="Change Password"),
    path('admin/create-driver/', DriverCreateView.as_view(), name="create driver"),
    path('admin/withdrawal/', WithdrawalSummaryAPIView.as_view(), name="admin-partner-withdrawal-overview"),
    path('admin/approve-withdrawals/<str:transaction_id>', ApproveWithdrawalView.as_view(), name="admin approve withdrawal"),
    path('driver-login/', DriverLoginView.as_view(), name="driver login"),
    path('setpin/partner/', SetPinView.as_view(), name="set pin"),
    path('delivery/initiateconfirm/', CreateDeliveryConfirmationView.as_view(), name="Initiate delivery"),
    path('deliery/confirm/', ConfirmDeliveryOTPView.as_view(), name="confirm delivery"),
    path('profile/update/partner/', UpdateProfileView.as_view(), name='update-profile'),
    path('retrieve-pin/partner/', RetrieveWithdrawalPinView.as_view(), name='retrieve-withdrawal-pin'),
    path('admin/orders/', AdminRecentOrdersView.as_view(), name='orders'),
    # path('request-reset-pin/partner/', RequestPinResetView.as_view(), name='request-reset-pin'),
    # path('reset-pin/partner/', ResetPinWithOTPView.as_view(), name='reset-pin-with-otp'),
    # path('investments/partner/', PartnerInvestmentsView.as_view(), name='partner-investment'),
    path('investments/partner/overview/', PartnerInvestmentOverview.as_view(), name='partner-investment-all-data'),
    path('transactionhistory/partner/', UserTransactionHistoryView.as_view(), name='transaction-history'),
    # path('admin/orders/history/', UserTransactionHistoryView.as_view(), name='order-history'),
    path('alltransactionHistory/admin/', AllTransactionsView.as_view(), name="all-transactions"),
    path('notifications/partner/', NotificationListView.as_view(), name="get-notified"),
    path('notification/read/', NotificationMarkAsReadView.as_view(), name="mark-read-notification"),
    path('getDetails/', PartnerDetailsView.as_view(), name="partner-details"),
    path("delivery/initiate/", CreateAndSendDeliveryOTPView.as_view(), name="initiate-delivery"),
    path("delivery/confirm/", ConfirmDeliveryView.as_view(), name="confirm-delivery"),
    path("vendors/create/", VendorCreateView.as_view(), name="vendor-create"),
    path("vendors/<str:vendor_id>/delete/", VendorDeleteView.as_view(), name="vendor-delete"),
    path("vendors/<str:vendor_id>/update/", VendorUpdateView.as_view(), name="vendor-update"),
    path("vendors/", VendorListView.as_view(), name="vendor-list"),
    path("admin/overview/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path('admin/partners/', AdminComprehensiveReportView.as_view(), name='admin-comprehensive-report'),
    path('admin/vendors/dashboard/', AdminVendorDashboardView.as_view(), name='admin-vendor-dashboard'),
    path('admin/vendors/<str:vendor_id>/', VendorDetailWithOrdersView.as_view(), name='vendor-detail-with-orders'),
    path('admin/partners/<int:partner_id>/', PartnerDetailWithInvestmentsView.as_view(), name='partner-list'),
    # path('admin/partners/', PartnerListView.as_view(), name='partner-detail-with-investmen/ts'),
    path('admin/orders/<str:order_id>/', AdminSingleROICycleBreakdownView.as_view(), name='partner-detail-with-investments'),
    path('admin/notification/', AdminNotificationListView.as_view(), name='admin-notification'),
    path('admin/updateStatus/', UpdateStatusView.as_view(), name='update-status'),
]